Update keyword regex
EdgeApp/edge-logs-server pull request #46
Opened 2023-03-08 02:16 UTC by paullinator

Only allow matches that start with " and end with \\" or \"

### CHANGELOG

 none

### Dependencies

 none

### Description

 none

2023-03-08 20:54 UTC, swansontec requested changes

2023-03-08 20:54 UTC, swansontec commented on src/indexApi.ts
> +  '___Internal Edge Key Names___',
This should be a comment, not a search term. This is a real TypeScript file, not a JSON, so we can use comments.

2023-03-08 20:54 UTC, swansontec commented on src/indexApi.ts
> +    const regexString = `"${word}(?:\\\\*)"`
You don't need the `(?:)` part, since the `*` operator has higher precedence than the "next-to" operator. So it can just be `"${word}\\\\*"`, and the `*` will only affect the `\`.

We needed parentheses in the GUI version to make the `|` operator do what we wanted, but you aren't using that here.

2023-03-09 01:03 UTC, paullinator commented on src/indexApi.ts
> +  '___Internal Edge Key Names___',
Good point. This was originally a JSON file which I then moved to typescript. Will fix

2023-03-09 03:12 UTC, swansontec approved these changes

2023-03-09 05:24 UTC, paullinator commented
/rebase

2023-03-09 05:26 UTC, merged